Repository youzan/vant-weapp, pull requests merged in 2025-04, with the labels that each got.

#5939 docs: fix typo in overlay and image
  packages/image/README.md
  packages/overlay/README.md
Labels: change: docs

#5874 docs: fix the recommended global font-family
  packages/common/README.md
Labels: change: docs

#5986 fix(button): fix button failure in open-type='contact' caused by business-id
  packages/action-sheet/test/__snapshots__/demo.spec.ts.snap
  packages/button/index.wxml
  packages/button/test/__snapshots__/demo.spec.ts.snap
  packages/card/test/__snapshots__/demo.spec.ts.snap
  packages/config-provider/test/__snapshots__/demo.spec.ts.snap
  packages/empty/test/__snapshots__/demo.spec.ts.snap
  packages/field/test/__snapshots__/demo.spec.ts.snap
  packages/goods-action/test/__snapshots__/demo.spec.ts.snap
  packages/notify/test/__snapshots__/demo.spec.ts.snap
  packages/overlay/test/__snapshots__/demo.spec.ts.snap
  packages/panel/test/__snapshots__/demo.spec.ts.snap
  packages/steps/test/__snapshots__/demo.spec.ts.snap
  packages/sticky/test/__snapshots__/demo.spec.ts.snap
  packages/submit-bar/test/__snapshots__/demo.spec.ts.snap
  packages/toast/test/__snapshots__/demo.spec.ts.snap
  packages/uploader/test/__snapshots__/demo.spec.ts.snap
Labels: change: fix

#5985 fix(dropdown-item): fix position error when root-portal
  packages/dropdown-item/dropdown-item.wxml
  packages/dropdown-item/index.wxml
Labels: change: fix

#5798 feat(radio-group): add custom-class prop support
  packages/radio-group/index.wxml
Labels: change: feat

#5991 fix(radio): fix test case error
  packages/radio/test/__snapshots__/demo.spec.ts.snap
Labels: change: fix

#5990 fix(notice-bar): fix display error when text value becomes shorter
  packages/notice-bar/index.ts
Labels: change: fix
